// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2TnevVpzp59I6EBh3JFYSTEvX3pHyjEc',
    appId: '1:387596651021:web:e5e58b8e94e3c429016344',
    messagingSenderId: '387596651021',
    projectId: 'ecobakoapp',
    authDomain: 'ecobakoapp.firebaseapp.com',
    storageBucket: 'ecobakoapp.appspot.com',
    measurementId: 'G-L6V4GHDE4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMYnUuxcY3l8mYMNe2UNsfzk_cjxjpz_8',
    appId: '1:387596651021:android:8ad1077efafbdedf016344',
    messagingSenderId: '387596651021',
    projectId: 'ecobakoapp',
    storageBucket: 'ecobakoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMowCm42EqdbfRBlNpYu_98gcatzpnuiM',
    appId: '1:387596651021:ios:debb92e73dfe84e4016344',
    messagingSenderId: '387596651021',
    projectId: 'ecobakoapp',
    storageBucket: 'ecobakoapp.appspot.com',
    androidClientId: '387596651021-bsvguc8q31h3s142eq0nuekl07n1h1s1.apps.googleusercontent.com',
    iosClientId: '387596651021-ujvpm7dds4ckebcg6q3gmo5qgjlkupdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecobakoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2TnevVpzp59I6EBh3JFYSTEvX3pHyjEc',
    appId: '1:387596651021:web:9829487f91b8e13d016344',
    messagingSenderId: '387596651021',
    projectId: 'ecobakoapp',
    authDomain: 'ecobakoapp.firebaseapp.com',
    storageBucket: 'ecobakoapp.appspot.com',
    measurementId: 'G-V6CKLB6RK2',
  );
}